### PR TITLE
F-14: Emesary MP notifications; (was: Fix for decoding missile pitch to 25.50 degs almost always.)

### PR DESCRIPTION
**Pull request by NikolaiVChr**
Seems to work now. :)

### CODE REVIEW

**Comment by Zaretto** [comment]
Thanks for the work.

Just two small questions;
1. What is the "small fix" to Emesary 
2. Why is it necessary to include Emesary from 2020.3

**Comment by NikolaiVChr** [comment]
To include it is needed due to the small fix to something Henning changed.
Its a fix you did, but the devs didn't cherrypick your fix into 2020.3
Check out conversation on mailing-list about it yesterday:

> I believe this snippet (at the bottom of this post) in emesary.nas from commit a13f9b3bb0e0c0ebecbbd3fdf4d793d3f7fdaeec
> will prevent emesary to work over MP.
> As when creating a new OutgoingMPBridge it does this:
> 
> var new_class = emesary.Recipient.new("OutgoingMPBridge "~_ident);
> 
> And then:
> 
> new_class.Transmitter.Register(new_class);
> 
> So this snippet below will return 0, as new_class does not have that function, its parent does have it though, but this check will bypass that:
> 
>         #not having a Receive function is an error
>         if (!isfunc(recipient["Receive"]))
>         {
>             logprint(DEV_ALERT, "Transmitter.Register: Error, argument has no Receive method!");
>             return 0;
>         }
> 
> Had it checked for recipient.Receive it would have found it. But then its not guarded for nil..
> 
> If I delete this snippet, emesary over MP works in 2020.3.1rc, and I can send and receive notifications from other MP aircraft.
> 
> Regards
> - Nikolai

**Comment by NikolaiVChr** [comment]
Also, we have so many warheads now that there was no room for cannon types.
So made those typeid negative.

**Comment by Zaretto** [comment]
@NikolaiVChr Can you test the F-14 against the release branch (without the local versions of Emesary modules) to confirm whether or not I've merged successfully.

The main problem that I've been having is with the horrible way that I originally implemented automatic typeid - this has caused all sorts of problems; it broke the F-16.

So what I've now decided is that unless a value of -1 is passed to Notification.new (in the third parameter _typeid) there will be no automatic id. Using -1 is deprecated now and hopefully the comments should make that clear.

Appreciate it if you could review what I've done for both the F-14 and the F-16

Thanks for doing this.

**Comment by NikolaiVChr** [comment]
emesary.nas I am using to test with is binary equal to emesary.nas in release/2020.3
The emesary_mp_bridge is also the same as the one I am testing with.
Used diff to compare.

I will try to test with them inside fgdata the next couple of days, but should give same result.

A couple of things though:
- I noticed in fgdata you listed ArmamentNotification_Id as 22, is it not allowed to be 19? If you want it to be 22, then I will change it, its 19 now in F14 etc.
- There seems to not be anything that stops the TransmitTimer in emesary_mp_bridge.nas when it disconnects, or am I looking wrong? Should there be, so the timer don't keep running..
- There is some print statements in emesary_mp_bridge, they should maybe be converted to log statements like in emesary.nas.

Been testing it last couple of days in 2020.3.1rc, its performing quite good. The queue limit was hit one time with having 6 missiles in the air at the same time, but that can be helped with some tuning I think.
Maybe there should be some sort of repeater in the aircraft for craters and such. So that pilots that log in after the crater notification still get to see it. Not sure if it is smart. Or do it by request somehow.

Thank you for merging the fixes in, one step closer to having everything work smoothly in 2020.3.1

**Comment by Zaretto** [comment]
You're right ArmamentNotification_Id should be 19; so I fixed this in 2020.3 and next.  

It appears that nothing stops the TransmitTimer; although there is a .Delete method it also appears as though this is currently unused (not called).

Under new guidelines all Nasal print statements should be converted - so I'll do that shortly.

**Comment by NikolaiVChr** [comment]
So for notification.Kind I suggest adding a number 5:
var CREATE = 1;
var MOVE = 2;
var DESTROY = 3;
var IMPACT = 4;
var REQUEST_ALL = 5;

Its meaning would be: Give me all persistent info. (for example craters in the area that was created while I was not online with mp msgs on).

**Comment by Zaretto** [comment]
Sounds like a good idea; and would also work effectively.

Is this something that you will be able to do or do you need my help?

**Comment by NikolaiVChr** [comment]
I did something simple already. :)

**Comment by NikolaiVChr** [comment]
F-14 plays nice with release/2020.3 so far :)

**Comment by Zaretto** [comment]
That's good; because I think the next RC is due in the next day or so once James has finished the "download your aircraft again" function

**Comment by NikolaiVChr** [comment]
So, I think we need another bridge[] property. For things like flares and other things, the inFlight bridge gets filled up too easy if using that when many missiles is in air. The armament bridge I think we should keep reserved for hits, craters and single events like that.
Can we use bridge[17]?

**Comment by Zaretto** [comment]
Adding another bridge for flares (etc) is a good idea. Bridges cost very little when nothing is transmitted.

The overriding limit is, of course, the remaining space in the MP packet. 

We can (and should) tune all of the bridge max length configuration to make maximum use of packet space; but being careful not to overflow.

**Pull request merged**
