### PR TITLE
Add IFF Channel Selection

### PR DESCRIPTION
**Pull request by Megaf**
Squash and merge please.
image

### CODE REVIEW

**Comment by Zaretto** [comment]
Thanks for the work; unfortunately it wasn't quite right but easy enough to fix. 

1. the <instrumentation> <iff> was in the wrong section
2. iff.nas needs to be in the <nasal> section

I believe this closes issue #133 @JMaverick16 can you check this please.

**Comment by JMaverick16** [comment]
Not sure why the < iff > part has been moved inside nasal

**Comment by Megaf** [comment]
> Not sure why the < iff > part has been moved inside nasal

I was told to by colin

**Comment by Megaf** [comment]
> Not sure why the < iff > part has been moved inside nasal

It was likely a mistake on my part. Only the file location was supposed to go there. Fixed.

**Comment by Megaf** [comment]
I just tested this over MP with a Viggen and worked fine, I was shown as friendly to him.
Changes can be merged if everyone is happy.

**Pull request merged**
