### PR TITLE
Bugfixes and improved accuracy for guided missiles

### PR DESCRIPTION
**Pull request by NikolaiVChr**
Hello Richard, I hope you like these changes.

### CODE REVIEW

**Comment by Zaretto** [comment]
Thanks for the change; I'm happy with them

Improvements to the way that missiles are implemented is something that I plan to come back to - probably once Stuart has made progress with the HLA - as we could have missiles, radar, etc. all in a separate HLA subsystem and then we will have a much better method of communicating between nodes that will hopefully work over multiplayer.

**Comment by NikolaiVChr** [comment]
That sounds interesting. Yes, HLA could bring many possibilities with it. :)

The last couple of days we have done lots of fights between F-14b, F-15C and JA-37, using a small improvised damage system, I added to those planes. It just formats and parses the MP messages in a certain way and then fail random failure-modes depending on distance and which kind of warhead it was. Is small, very simple, and we had lots of fun with it. If you want I can make a pull-request with that? I can make it need a property to be enabled, like the hit messages does.

**Comment by Zaretto** [comment]
I think I'd rather do this with bombable support. 

I've added bombable to the F-14 and all I needed to do was to put the Nasal (from the wiki) into the model xml and it was easy - so I'd suggest that we all add bombable.

I've made it kill the engines and a wing drop off when the aircraft gets over 70% damaged - it also works well with guns.

So overall we should use bombable and not the MP chat IMO

The F-15 will get bombable shortly once I've got more missiles working on the F-14

**Comment by NikolaiVChr** [comment]
I agree that MP messages is not a long term solution. I hate when trolls use our planes to shoot at civilian traffic.

But Bombable is heavy on the CPU, so I do not like it. But yes, using MP strings as Bombable does is the way to go, will also allow us to get rid of those MP messages. Will look at Shinobi's code when he is finished with it, should be able to let missiles hit flares and such. And think he will use MP strings, at least that's what we agreed on before he started. That system can probably be upgraded to give damage. We'll see what happens, but in the end I think we should use the same system, so that damage works across aircraft types.

More missiles on the F-14, great! Already scared of it if you give it the phoenix.

**Comment by Zaretto** [comment]
I'd like to remove the use of mp messaging to announce missiles - but at the moment it is the only way that a pilot knows they have been fired upon. 

I'm trying to work out how to resolve this so that the ECM systems will pickup and track the missiles; but this isn't easy. Firstly I've got to understand what bombable can do and if the method it uses to communicate is suitable; and if that doesn't work I've got a scheme where the missile launch notifies over MP and then the targetted aircraft will also create a local version of the missile for tracking purposes. 

I've not seen any evidence of bombable using a lot of CPU - have you got any information / evidence of what it's doing to slow things down?

I'm working on both the AIM-7 and AIM-54 and possibly the AIM-120 but that might only be on the -D variant as the AIM-54 was phased out in 2004.

**Comment by NikolaiVChr** [comment]
My only evidence is my own experience. But I like my way of dealing damage more that a simple percentage.

Bombable uses MP strings to communicate I believe, which is also the way to go I think. I just don't like bombable.

I don't know how far Shinobi is with his flare system, but I will ask him.

In the end I think we should have systems that can do these things, which I think is quite easy to achieve:

- rear aspect only heat seeking missiles
- locking on to flares, especially if aircraft is presenting front-aspect.
- warning of enemy lock
- warning of enemy missile release (and position?)
- damage (using failure system is way to go in my opinion)
- losing radar (aircraft/missile) lock at ECM/chaff
- semi-radar guided missiles (already done)

**Pull request merged**
